# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=1000)),
                ('short_description', models.CharField(max_length=1000)),
                ('photo_url', models.CharField(max_length=1000)),
                ('deal_link', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=5000)),
                ('old_price', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
