# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0003_auto_20170729_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='slug'),
        ),
    ]
