# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0008_auto_20170925_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='website',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.CharField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=5000),
        ),
    ]
