# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestdeal', '0009_auto_20171023_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.CharField(max_length=7000, null=True),
        ),
    ]
